apiVersion: v1
kind: Pod
metadata:
  name: helloApp-pod
  labels:
    tier: frontend
spec:
  containers:
  - name: tomcat-image
    image: udiscopotato/hello-app:v1
    ports:
      - containerPort: 8080
    volumeMounts:
    - name: my-volume
      mountPath: /tmp
  volumes:
  - name: my-volume
