replicaCount: 1

image:
  repository: udiscopotato/hello-app
  tag: "v1"
  pullPolicy: IfNotPresent

service:
  #protocol: TCP
  type: NodePort
  port: 8080
  targetPort: 8080
  #nodePort: 30009

env:
  name: dev
